### ISSUE TITLE
multiParser on micro820 returns empty

### ISSUE THREAD

**Issue by limsan** [dmroeder/pylogix#10]
works on single tag, but multiTag still have problem
stripped = data[50:]   # stripped is empty but data [0:50} there are bytes
if I unpack_from('<H', data, 0)[0] , it shows 112

**Comment by dmroeder** [comment]
Thanks for the info, I'll dig into this tomorrow when I have access to a Mirco820

**Comment by dmroeder** [comment]
Turns out that the Micro8xx doesn't support the multi-read service.  I'll make some changes so it will fail more gracefully.

**Comment by limsan** [comment]
Thank You, for clearing it up, a great project btw, I like your approach better, straight-forward & gets the job done rather than others similar, learned a lot from your code. thanks

**Comment by dmroeder** [comment]
I appreciate the kind words.  I tried to make it simple to use, mostly because I'm a simpleton!
