### ISSUE TITLE
Trouble reading tags inside an array.  Possibly a UDT?

### ISSUE THREAD

**Issue by cstrutton** [dmroeder/pylogix#107]
I am a python programmer not a PLC programmer.  Your library is simply the greatest.  Thanks for all your hard work.  
I use RSLinx Classic to find out what tags I want to investigate.  

I was able to read DailyTotal:
![hourly parts](https://user-images.githubusercontent.com/4387469/75374091-a1710280-5899-11ea-828a-dc5e24ba5b69.png)
using this code:
![hourly code](https://user-images.githubusercontent.com/4387469/75374114-adf55b00-5899-11ea-8c40-a896f4394455.png)

Unfortunately, this DailyTotal tag:
![prev day parts](https://user-images.githubusercontent.com/4387469/75374180-c82f3900-5899-11ea-8b0c-3f71ce4db5f2.png)
does not work with this code:
![prev day code](https://user-images.githubusercontent.com/4387469/75374203-d0877400-5899-11ea-81e3-d15344b109a9.png)
Am I addressing this tag wrong? Or am I missing something?

**Comment by kodaman2** [comment]
Hey there, what happens if you do:


```
Program:Production.ProductionData.PrevDayHourlyParts[0].Total.DailyTotal
```

Next time please paste your python code rather than screenshots, and format with the code markdown:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by dmroeder** [comment]
That is quite the UDT you have there.  It should be possible.  What does ret.Status print out?

Can you do this in the python interpreter
```
import pylogix
pylogix.__version__
```

**Comment by cstrutton** [comment]
dmroeder:
Python version 3.8.1, Pylogix version 0.6.1
HourlyParts is a separate tree that I read in the first example.  
ret.Status is Path segment error
LOL...yes it is quite the UDT (if that is what it is)

kodaman2:
I would never have thought to try that but it works.  It even kinda makes sense.
I apologize for the code pics.  I had to take pics of RSLinx so I did the same with VSCode without thinking.

Thanks for everyone's quick responses.  This is a great project enabling guys like me to get even deeper in over their heads.  Love it!
That being said, I have access to a multitude of PLC (several hundred on my shop floor).  If I can help with testing, let me know, I would love to contribute if I am able.

**Comment by dmroeder** [comment]
Oh duh, I see it now.  Got confused on which screenshot I was looking at.  Would you be willing to export that UDT and email it to me?  Assuming that there is actually no typo, I wonder if there is something with how long it is.

**Comment by kodaman2** [comment]
> kodaman2:
> I would never have thought to try that but it works. It even kinda makes sense.
> I apologize for the code pics. I had to take pics of RSLinx so I did the same with VSCode without thinking.
> 
> Thanks for everyone's quick responses. This is a great project enabling guys like me to get even deeper in over their heads. Love it!
> That being said, I have access to a multitude of PLC (several hundred on my shop floor). If I can help with testing, let me know, I would love to contribute if I am able.

Yeah when expanding UDTs the array name gets repeated on the drilldown but for reading the tag you only need to know the index:

```
PrevDayHourlyParts[0]
```

**Comment by dmroeder** [comment]
OOOOOHHHH, good call @kodaman2.   I missed that point in your original reply.  My game is off. 

Disregard sending me that @cstrutton, I didn't quite grasp that it worked when you tried what kodaman recommended.

**Comment by dmroeder** [comment]
Actually @cstrutton , if you get time, send me an email, we can talk about what kind of hardware you have at your disposal.

**Comment by dmroeder** [comment]
@cstrutton , if you want to help out you could check out issue #110 and give me feedback on routing.
