### ISSUE TITLE
 read expansion cards

### ISSUE THREAD

**Issue by Ivan197** [dmroeder/pylogix#114]
Hello, I have a question...
How could I read data from expansion cards ?, from analog inputs and analog outputs.

Being of the same Allen-Bradley brand.

**Comment by kodaman2** [comment]
Not entirely sure I follow the question. Pylogix reads tags, so just read the tag. No need to worry about the modules. 

As long as the modules are in the same rack as a supported PLC controllogix, compactlogix, you can read any tag.

**Comment by dmroeder** [comment]
@Ivan197, are there anymore details on what you are trying to accomplish?  What do you mean by "expansion cards", can you give part numbers?
