### ISSUE TITLE
Question for device 5069-L310ER COMPACTLOGIX

### ISSUE THREAD

**Issue by kajatesar** [dmroeder/pylogix#138]
## Type of issue

- [ ] Bug
- [ ] Feature Request
- [x] Question
- [ ] Other

## Question

Hello, is your library compatible with the following device?

**PLC: 5069-L310ER COMPACTLOGIX 1MB**

Thanks very much!

**Comment by kodaman2** [comment]
Hello, yes, it is.

**Comment by kodaman2** [comment]
By the way is probably quicker to  use pylogix tester to get this answer too, but as a rule of thumb all compactlogix and controllogix are supported through etherip protocol.

**Comment by kajatesar** [comment]
@kodaman2 Yeah, I know but unfortunately I don't have the device yet. Thank you!

**Comment by kodaman2** [comment]
> @kodaman2 Yeah, I know but unfortunately I don't have the device yet. Thank you!

No problem, when you get your plc, if you have any problems let us know.
