### ISSUE TITLE
Forcing allen bradley outputs

### ISSUE THREAD

**Issue by lyndoncoin** [dmroeder/pylogix#139]
Hi, Are you are to use this library to force digital outputs?

**Comment by dmroeder** [comment]
You cannot.

**Comment by kodaman2** [comment]
Off-topic, what are you trying to do? Typically forcing should be only for troubleshooting and last resort type of deal and used with Rockwell Software. I've been in the Automation industry for 10+ years and I've had to force an I/O less than I can count with one hand. Forces should never be used in a production environment to get equipment going.
