### ISSUE TITLE
unknown tag: __CONTAINER

### ISSUE THREAD

**Issue by AndrewStuhr** [dmroeder/pylogix#143]
Hello

I'm reading the tag list from a 5069-L3100ERM/A.  One of the tags returned is called "__CONTAINER".  It is type DINT.  When I read it's value, pylogix returns 0.  This tag wasn't added by the programmer; in fact the programmer doesn't know what it is.

Do you know about this tag?  It seems like an internal tag to the PLC.  In general, do you know if tags that begin with 2 underscores are internal tags?

**Comment by ottowayi** [comment]
That's a system tag that isn't being filtered out.
![image](https://user-images.githubusercontent.com/5274950/92808729-9b4bfa80-f381-11ea-985e-8d6948d3edc1.png)

**Comment by AndrewStuhr** [comment]
You're the man ottowayi.

So is this something that pylogix should filter, or I as the user should filter?

Thanks!

**Comment by dmroeder** [comment]
Oh thanks @ottowayi  and @AndrewStuhr , I'll dig into that.

**Comment by ottowayi** [comment]
The only rule I skipped was the I kept ones with colons in the name, because I wanted (well, actually someone opened an issue saying they were missing) module-defined tags in the list.

**Comment by dmroeder** [comment]
That should be filtered out now @AndrewStuhr, as well as the AOI (UDI:) from issue #128
