### ISSUE TITLE
ESP32 micropython support

### ISSUE THREAD

**Issue by ivancho523** [dmroeder/pylogix#145]
Hello
How can I use this library with an ESP32, what changes should I make to be able to use it in a microcontroller? is it possible to use it with micropython?

**Comment by kodaman2** [comment]
Hi, we don't explicitly support micropython. I am not even sure if micropython has all the core modules that pylogix needs like socket, etc.

Also you need ethernet for pylogix to communicate with the plc, wireless communication won't do.

By all means let us know if you do get it working. I just gave micropython a quick read and it does come with some core modules but prefixed with a `u` see below. So you will have to change those modules like `socket` to `usocket` if there's a module needed and not on micropython you'll have to learn how to compile and optimize that module for micropython. 

http://docs.micropython.org/en/latest/library/index.html

Best thing I can say is just to buy a linux based microcontroller that has raspbian like raspberry pi or zero or something alike there are several clones. This way you save a lot of time and frustration.

**Comment by kodaman2** [comment]
Closing ticket, if you need any further assistance let us know.

**Comment by TheFern2** [comment]
@ivancho523 probably 3 years too late but nevertheless better late than never. We officially support micropython 1.20+. Check out the documentation for more information.
