### ISSUE TITLE
Can pylogix read Micro800 program Tags?

### ISSUE THREAD

**Issue by 10062244** [dmroeder/pylogix#149]
Hello,
Ive been trying to read some program tags out of a Micro800 program with no luck. I can read read controller scope tags fine. Is there a change in the syntax when reading from a Micro800 program vs a controllogix program? I did the Program:programName.tagName scheme. Also, the GetProgramsList function doesnt seem to work either for my Micro. 

Thanks

**Comment by TheFern2** [comment]
Hi, you can only read global variables (controller scope) on micro800.

https://github.com/dmroeder/pylogix/issues/66#issuecomment-533271724

**Comment by dmroeder** [comment]
Rockwell doesn't provide a documented way to read local variables.  Also, the Micro8xx series doesn't support a lot of the services that the Logix platform supports.  These features only work with the Logix platform, it's a limitation of the Micro8xx.
