### ISSUE TITLE
Pylogix as a part of a simple Web Project

### ISSUE THREAD

**Issue by GitHubDragonFly** [dmroeder/pylogix#164]
This is only intended to show a possible way of using the pylogix library to read tags and show their values in a web page:

https://github.com/GitHubDragonFly/WebProject

Close this non-issue whenever you want.

**Comment by TheFern2** [comment]
@GitHubDragonFly That is very cool, I had built a very simple similar API a while back in flask though. 
https://github.com/TheFern2/pylogix-api

@dmroeder I think it might be a good idea to add a doc with all these cool projects built with pylogix.

**Comment by GitHubDragonFly** [comment]
I like your API, since it's somewhat simpler.

If you would like some improvements here is the app.py file that allows reading array of tags as well as elements of 1-dimensional array, addressed like this:

localhost:5000/pylogix/v1.0/plc/192.168.0.10/0/tags/[someTag1, someTag2, someTag3, someTag4]
localhost:5000/pylogix/v1.0/plc/192.168.0.10/0/tags/someArrayTag[x]{y}

Both x and y need to be within the array bounds and also y > 0.

If you like it then just include it in your repo and spare me from submitting a PR.

[app.zip](https://github.com/dmroeder/pylogix/files/6120316/app.zip)

Your idea about creating a doc or a text file with all the cool project links sounds good to me and would poke people in the eye if it is a part of "examples".

I will eventually go ahead and close this non-issue.

**Comment by GitHubDragonFly** [comment]
There was one typo so I just replaced the file in my previous post.

**Comment by TheFern2** [comment]
@GitHubDragonFly Thanks for your contribution, I've added you to that commit for proper credit.

**Comment by GitHubDragonFly** [comment]
If you ever go about creating a list of pylogix projects, here is another one that was done couple of years ago and does require some understanding:

    https://github.com/tdw1004/PylogixGUI

**Comment by GitHubDragonFly** [comment]
If you might ever be interested in running this web project in Linux, I did bother converting the batch file to shell script.

It does need to be first made executable by running chmod +x on it.

**Comment by GitHubDragonFly** [comment]
Here are some pictures of how pylogix can also be used with Node-RED (this was done on Raspberry Pi 2).

It is a modified version of this example:  https://flows.nodered.org/flow/778859ca2503db35ff0e12341508efef

Some benefits of Node-RED would be already available GUI elements and other packages (like pythonshell used in this example), minimal python code, cyclic reading and live dashboard updates.

![Node-RED Pylogix 1](https://user-images.githubusercontent.com/69928501/112791057-b258ee00-902e-11eb-8252-4eb9fb5fda3d.png)

![Node-RED Pylogix 2](https://user-images.githubusercontent.com/69928501/112791058-b2f18480-902e-11eb-9c68-08c9bd506e40.png)

**Comment by GitHubDragonFly** [comment]
There is a new repo for this Node-RED example project:  https://github.com/GitHubDragonFly/Node-RED_PLC_Example

It is a hybrid project, using pylogix library for tag reading and using pycomm3 library for the device discovery and tag listing.
