### ISSUE TITLE
I was trying to read data from PLC Micro Logics 1400(Allen Bradley) through Python and dump it to MS SQL, then "can only concatenate str (not "bytes") to str" this error occurred while reading data from PLC Micro Logics 1400. I will attach the python program which I am currently using. If anyone knows the solution for this kindly help me out with it. https://drive.google.com/file/d/1C-g4M5YhtsvvTCaDnz3jLhYuRg64E-8f/view?usp=sharing

### ISSUE THREAD

**Issue by GaganIK22** [dmroeder/pylogix#165]
### Preflight checks

- [ ] Have you tried the examples?
- [ ] Have you tried [pylogix-tester](https://github.com/kodaman2/pylogix-tester)?
- [ ] Have you read previous issues?

## Type of issue

- [ ] Bug
- [ ] Feature Request
- [x] Question
- [ ] Other
[question.txt](https://github.com/dmroeder/pylogix/files/6204253/question.txt)
[question.txt](https://github.com/dmroeder/pylogix/files/6204271/question.txt)

> Delete items that do not apply below.

## Code

Please provide a minimal, reproducible example

## Versions

Include versions to

- pylogix:
- python:
- OS:

**Comment by TheFern2** [comment]
Hi there @GaganIK22 four things just for your future reference:

1) The question should go into the body of the question, not the title. Look into other issues for how is supposed to be done.
https://github.com/dmroeder/pylogix/issues

2) Always post code in the issue itself, not some third party service. So other people can benefit without having to download. Is also safer to see code here, than download some random file off the internet.

3) Preflight checks are there for a reason

4) Micrologix is not supported as stated in the readme. https://github.com/dmroeder/pylogix

**Comment by GaganIK22** [comment]
Thank you.
