### ISSUE TITLE
Unknown Error 255 on Multi-Write when including a string

### ISSUE THREAD

**Issue by Destination2Unknown** [dmroeder/pylogix#193]
### Preflight checks

Before you post an issue, ensure you have tried the minimal examples within the repo, or tried the pylogix-tester.

- [x] Have you tried the [examples](https://github.com/dmroeder/pylogix/tree/master/examples)?
- [x] Have you tried [pylogix-tester](https://github.com/TheFern2/pylogix-tester)?
- [x] Have you read previous issues?

## Type of issue

- [ ] Bug
- [ ] Feature Request
- [x] Question
- [ ] Other

## Description of issue
Writing strings individually works perfect but trying to write multiple Strings does not. 

Examples:
[("MyString", "This is a String"),("MyDint", 10), ("MyInt", 3)]
MyString - Unknown Error 255
MyDint - Success
MtInt - Success

[("MyString", "This is a String")]
MyString - Success

[("MyString", "This is a String"),("MyString2", "This is a String2")]
MyString - Unknown Error 255
MyString2 - Unknown Error 255

## Code

from pylogix import PLC
with PLC("192.168.123.100") as comm:
    comm.ProcessorSlot = 2
    request = [("MyString", "This is a String"),("MyDint", 10), ("MyInt", 3)]
    ret = comm.Write(request)
    for r in ret:
        print(r.TagName, r.Value, r.Status)

Prints:
Unknown Error 255 for the string but everything else succeeds.

Any Ideas?

**Comment by dmroeder** [comment]
Thanks.  I have a fix for this.

**Comment by Destination2Unknown** [comment]
So it wasn't just me then...
Sweet, is that good to go then?

**Comment by dmroeder** [comment]
Not just you, legit bug.  The latest update fixed it for me.  Try it out and let me know if you agree.

**Comment by Destination2Unknown** [comment]
When I try to upgrade via "pip install pylogix --upgrade" it is still showing up as 0.7.16, do I need to manually upgrade?

**Comment by TheFern2** [comment]
> When I try to upgrade via "pip install pylogix --upgrade" it is still showing up as 0.7.16, do I need to manually upgrade?

Instructions are on the readme. See screenshot below, you have two options clone as shown in the picture, or click the download button on the repo:


https://github.com/dmroeder/pylogix
![image](https://user-images.githubusercontent.com/10265682/154329437-f171a6c5-5ee6-461e-8c38-ec8eca46cc20.png)
