### ISSUE TITLE
Issues connecting to emulate

### ISSUE THREAD

**Issue by sethoon88** [dmroeder/pylogix#221]
Still having trouble with connecting to an emulator. connection size set to 504 and ip address set to the PC.  Am i missing something else?  thanks!
![em](https://user-images.githubusercontent.com/104997988/227284046-2c4f9fdc-c9cf-4958-ac5b-3a5157e556d7.PNG)

**Comment by evaldes2015** [comment]
I think I tried this some time ago and couldn't get it to work

**Comment by dmroeder** [comment]
Open RSLinx Enterprise/FactoryTalk Linx, right click on the Ethernet driver, Properties > Advnaced.  Check the box "Listen on Ethernet I/P encapsulation ports

**Comment by dhunt84971** [comment]
Whoa!  Okay.  Learned something new, today.  Removing my misleading answer.

**Comment by dmroeder** [comment]
@dhunt84971, no worries. there was a point where I was confidant that you could not communicate with emulate in this way.  Even after I tested it and it worked for me, it still didn't work for others.  I later learned about that configuration.

**Comment by DasDuneTech** [comment]
Hi, I am not using Factory Talk, only RSLinx Classic Gateway and Emulate 5000, everything works fine with Logix Designer 5000 btw. I get : Unknown error [WinError 10061]... with pyLogix.  Is there any setting I can do on RSlinx ?   see below a screen shot on the advanced tab in RSLinx. Thanks!
![image](https://github.com/dmroeder/pylogix/assets/70418130/3ebe5313-1b84-40e1-bdb0-c227b4a5eadb)

**Comment by dmroeder** [comment]
I'm only aware of this option being available with FTL.  So in order to do this, you will probably have to install FTL.  You wouldn't be "using" FTL to communicate, it just acts as a bridge, accepting the connection and forwarding it to Emulate AFAIK.
