### ISSUE TITLE
micro850 connection

### ISSUE THREAD

**Issue by fernandoamorim1703** [dmroeder/pylogix#222]
A question, I'm trying to use node-red's ethernet/ip node, I made some changes to the library because of the multiple service.

But I am facing connection problem. The connection is not maintained, the PLC always sends an FYN flag or even an RST.

Could you tell me why?

**Comment by dmroeder** [comment]
Why are you opening an issue on my project instead of node red's EIP module?

**Comment by fernandoamorim1703** [comment]
I wanted to better understand the communication with the micro850

**Comment by dmroeder** [comment]
I posted packets below of wireshark packets with the difference between CLX and Micro800.

https://www.plctalk.net/qanda/showpost.php?p=930765&postcount=28

**Comment by dmroeder** [comment]
I'd pay close attention to the forward open.  Micro800 doesn't use the port segment, which is what those packets are showing.  I think I showed more of that if you read further in that thread.
