### ISSUE TITLE
cannot get a tag list

### ISSUE THREAD

**Issue by bartmch** [dmroeder/pylogix#228]
### Preflight checks

Before you post an issue, ensure you have tried the minimal examples within the repo, or tried the pylogix-tester.

- [X] Have you tried the [examples](https://github.com/dmroeder/pylogix/tree/master/examples)?
- [X] Have you tried [pylogix-tester](https://github.com/TheFern2/pylogix-tester)?
- [X] Have you read previous issues?
- [X] Is this a supported Rockwell PLC?

## Type of issue

- [ ] Bug
- [ ] Feature Request
- [X] Question
- [ ] Other

> Delete items that do not apply below.

## Description of issue
I'm trying to run example 28. Unfortunately, it already throws an error at line 9.
<img width="650" alt="image" src="https://github.com/dmroeder/pylogix/assets/10415569/5197df72-24ca-49f6-a6f5-6a5a38b2774e">

I'm running this script because I wasn't able to discover any tags using:
<img width="313" alt="image" src="https://github.com/dmroeder/pylogix/assets/10415569/3947c7c4-a998-4bb9-8683-f3e656920736">
`None None Forward open failed`

**Comment by dmroeder** [comment]
What PLC model (and Ethernet module if CLX)?

**Comment by bartmch** [comment]
The PLC is Rockwell Allen Bradley CompactLogix L24 ER QBB1B. Thanks @dmroeder !

**Comment by bartmch** [comment]
It works no. I was using the wrong IP address facepalm

    comm = PLC()
    comm.IPAddress = '192.168.0.50'

    comm.Read('E_TC')
    tags = comm.GetTagList()
