### ISSUE TITLE
Is it possible to inhibit a periodic task?

### ISSUE THREAD

**Issue by ramezanifar** [dmroeder/pylogix#229]
In RSLogix a task type can be Continuous, Periodic, Event. There is also a checkbox to inhibit a task.
Does anyone know if we can enable/disable the inhibit setting via pylogix? This is useful when running automated tests to disable the PLC logic to manipulate the tags from pylogix and avoid PLC logic stumping on the injected values.
Thank you in advance

**Comment by TheFern2** [comment]
This is not possible with pylogix. I recommend looking into autoit scripting, is one way to automate it through the Studio5K gui.

**Comment by dmroeder** [comment]
Add SSV's to inhibit the modules with a bool of choice ahead of them.  Then write to that bool with pylogix.  I think that is about all you will be able to do.
