### ISSUE TITLE
Question about tag syntax

### ISSUE THREAD

**Issue by TheFern2** [dmroeder/pylogix#28]
Maybe I am doing this wrong, or there is no way to parse the tag as it stands.

This works:
`Program:DW_Fast.VP_WRK_CreepEncoderALastscan`
But this doesn't:
`Program:DW_Fast.DW_VP.INP_DWAEncoderPresentValue`
both tags are DINT

I am assuming pylogix can only take program, and tag without having anything else in the middle with a dot?

**Comment by dmroeder** [comment]
There is no reason that I know of that reading a program scoped tag that is a UDT wouldn't work.  I have a program that contains every variation of tag type that I can think of (basic tags, arrays, UDT's, multi-dimensional arrays, UDT Arrays, etc) in both controller and program scope.  I typically run a test on that program that reads/writes all of the tags (controller and program scope) before I commit changes.

Could you possibly send me the program?  If sending the program is out of the question, maybe you could export the UDT and send it to me, I'll try and run the same test.

**Comment by kodaman2** [comment]
Here's the udt in question, no rush, I was able to get the tag from the top one, which comes from a MOV from the second tag. 
[UDT_DW_VPROFILE.L5X.txt](https://github.com/dmroeder/pylogix/files/2524103/UDT_DW_VPROFILE.L5X.txt)

Traceback (most recent call last):
```
  File "~\dw_encoder_troubleshooter.py", line 39, in <module>
    dwx_encoder = ex_read('Program:DW_Fast.DW_VP.INP_DWAEncoderPresentValue')
  File "~\dw_encoder_troubleshooter.py", line 8, in ex_read
    return comm.Read(tag)
  File "C:\Python34\lib\site-packages\pylogix\eip.py", line 90, in Read
    return _readTag(self, args[0], 1)
  File "C:\Python34\lib\site-packages\pylogix\eip.py", line 160, in _readTag
    InitialRead(self, t, b)
  File "C:\Python34\lib\site-packages\pylogix\eip.py", line 1178, in InitialRead
    raise ValueError(cipErrorCodes[status])
ValueError: Path segment error
```

**Comment by dmroeder** [comment]
Looking at your tag list, DW_VP is a controller scoped tag.

**Comment by dmroeder** [comment]
Haha, no problem, glad it was easy!
