### ISSUE TITLE
test.Read("tagname") returns None

### ISSUE THREAD

**Issue by usaish** [dmroeder/pylogix#29]
HI,

First, thank you for this amazing library.

As mentioned, I am able to connect to the PLC and extract the tag list. However, when I try to print a tag value, it shows None. e.g.

>>> value = test.Read("testbit")
>>> print (value)
None
>>> 
<img width="346" alt="screen shot 2018-10-29 at 2 35 48 pm" src="https://user-images.githubusercontent.com/3359334/47672276-f4dd1e80-db87-11e8-8339-d84f890c0703.png">

**Comment by dmroeder** [comment]
This is a sign that it is not actually connecting to the PLC.  If you would perform your test while running Wireshark, I can look over the file and verify, you can email it directly to me.

It should be telling you the problem though, I'll make some changes here to better inform users.

**Comment by dmroeder** [comment]
I pushed a change that should raise an exception if the initial connection to the PLC fails, rather than return None.  

Typically what you were seeing was a result of the PLC IP address being wrong, or the network adapter not being available (disconnected or disabled).

**Comment by usaish** [comment]
You are right. The plc wasn’t communicated. I restarted the comms and it worked. Thanks for adding the exception

**Comment by dmroeder** [comment]
Great thanks for the update!
