### ISSUE TITLE
Set PLC DateTime

### ISSUE THREAD

**Issue by MarcosZornitta** [dmroeder/pylogix#3]
Can i set PLC DateTime? How?

**Comment by dmroeder** [comment]
You cannot, I have not implemented it.  I'll see what I can do though.

**Comment by MarcosZornitta** [comment]
Ok, thx

**Comment by dmroeder** [comment]
Hey Marcos, check out the latest code.  I added .SetPLCTime().  This will use your computers time to set the PLC clock.  I was a little slow getting to that one.

**Comment by MarcosZornitta** [comment]
that's worked, thanks

**Comment by dmroeder** [comment]
Great thanks for the update.
