### ISSUE TITLE
Unexpected Individual Read Result from Array

### ISSUE THREAD

**Issue by kodaman2** [dmroeder/pylogix#33]
Question: I have a file with 18000 or so tags. I read all 1800 tags, then check current status in the PLC, then write to file. Roughly takes 37s for the whole operations.

```
Program:MyProgram.MyTag[0]
Program:MyProgram.MyTag[1]
...
Program:MyProgram.MyTag[299]
```

I am doing the read tags as follows:
`test.Read(tag)`

If I run my program it will raise an exception "Read failed Unkown Error" exactly at:
`Program:MyProgram.MyTag[160]`

My first thought was that maybe I was reading the tags too quickly, so I added a sleep(1) in between reads but exactly at 160 the exception is thrown.

I figure maybe there's a limit, tags from 0 to 159 are read fine is  boolean and I print out to the console to check True and False were coming across. As a test I deleted all tags from this array starting at [160]. I checked the whole file and no other array went over 160. After deleting 160-299 lines from that array tag, I ran the program and it executed fine read all tags and wrote to the file.

Am I overlooking something? Have you come across this before?

**Comment by dmroeder** [comment]
No you are not overlooking and no I have not come across this before.  I see what is going on though, I have an issue with how I'm handling my nemesis, BOOL arrays.  I'll get it fixed and give you some details on what was going wrong.

**Comment by dmroeder** [comment]
Try the latest commit, let me know what you think

**Comment by kodaman2** [comment]
Nice, issue fixed! Complete boolean array of 300 indices was read with no problems.
