### ISSUE TITLE
read array of boolean

### ISSUE THREAD

**Issue by enriba** [dmroeder/pylogix#44]
I have an array of booleans of length 127.
why the function Read("arrayName", 127) gives me error?

I can only read one bit at a time with the function Read("arrayName[index]")

**Comment by evaldes2015** [comment]
I just did a test read of 128 elements from a BOOL array. It worked fine.

Are you sure your array length is correct in the PLC? Can you send an image of the controller tag configuration?

**Comment by enriba** [comment]
![Cattura](https://user-images.githubusercontent.com/38317379/54840178-af52f680-4ccc-11e9-81e4-148da92b30c9.PNG)

**Comment by evaldes2015** [comment]
print(comm.Read('test9', 128))

works just fine reading:
![image](https://user-images.githubusercontent.com/15380210/54840404-5cb11480-4ca3-11e9-88e5-a9c93cfe893c.png)

Don't know what to say. Double check your spelling?

**Comment by enriba** [comment]
I'm a idiot, the function read() work very well.
I use pylogix in a flask restful api, the error is in my flask code
