### ISSUE TITLE
Failing to receive data when closing the connection

### ISSUE THREAD

**Issue by Derriick** [dmroeder/pylogix#52]
Hello,

When I call the Close() method, the execution does not reach self.Connect.Close(), which means that the TCP session with the PLC remains active (seen with Wireshark).
This is due to this line:
https://github.com/dmroeder/pylogix/blob/31cf687aeecea448fb07ab8a72186685ff9fd1c2/pylogix/eip.py#L816

Is this call to recv_data() necessary? It fails only in this case (via the Close() method), when self.Socket.recv(4096) is called:
https://github.com/dmroeder/pylogix/blob/31cf687aeecea448fb07ab8a72186685ff9fd1c2/pylogix/eip.py#L1443

For the moment, simply commenting the first line is enough for me.

**Comment by dmroeder** [comment]
Good call Derriick.  Receiving data from either forward close or unregister session seems a bit unnecessary, since we're closing the connection.  I'll fix it here in a bit, thanks!

**Comment by Derriick** [comment]
Great! Thank you for your answer and your work!
