### ISSUE TITLE
Using PL to Send Images to PLC

### ISSUE THREAD

**Issue by KalebSixto** [dmroeder/pylogix#59]
Is there a way to use Pylogix to send an image or multiple images to the PLC?

**Comment by evaldes2015** [comment]
You could write it as a DINT, INT or SINT array. 
Why do you want to do this?

**Comment by dmroeder** [comment]
Could you please clarify what you are trying to do?  I don't understand what you mean by "send an image".

**Comment by KalebSixto** [comment]
I am processing a changing graph using matplotlib and seaborn. I want to send the images of the updating graphs to a control logix plc.

**Comment by evaldes2015** [comment]
What would the PLC do with it?

**Comment by KalebSixto** [comment]
The plc would output the images to a tool or monitor.

**Comment by evaldes2015** [comment]
You're using the PLC to transfer the image? Surely there are better mechanisms than this.

**Comment by KalebSixto** [comment]
I most certainly agree, but where i work they want to use the PLC. I'm not certain why. I am merely following instructions.

**Comment by evaldes2015** [comment]
The max array size in ControlLogix is 2MB. Will your image fit?
Another issue is performance. Assuming it takes 6ms to transfer 100 array elements to the PLC, it would take 30 seconds to write a 500KB image. This is best case.

**Comment by KalebSixto** [comment]
I will have to check into the size of the images im outputting, however I am certain at least one of the images is too large. You mentioned before that there might be a better way. What would you recommend?

**Comment by evaldes2015** [comment]
It depends. Where are the images coming from? Where are they going? Can they be saved as files? It all depends on the details. Can you FTP them from one system to another? Can you write them to a shared folder?

**Comment by KalebSixto** [comment]
The images are coming from a computer in python. They are being outputted to machine monitors inside of labs. The rest of the questions I will have to look into as I am uncertain due to my lack of experience with matplotlib.

**Comment by evaldes2015** [comment]
You should be able to write image files in various formats from Python.

**Comment by KalebSixto** [comment]
I got permission to not use the plc for the image processing. Thanks for the help!
