### ISSUE TITLE
Read UDT Array

### ISSUE THREAD

**Issue by MarcosZornitta** [dmroeder/pylogix#6]
How can I read all the elements or just one selected of a UDT array?

Ex.:  My UDT:

**Products**
 - Code
 - Name
 - Counter

So I try to read a Products_DB array of Products [300], but when I try to read from Read ('Products_DB', 300) it returns only the code for each position and not all elements.

Any way to solve this?

**Comment by dmroeder** [comment]
There currently is no way to read UDT's.  Dealing with UDT's is something that I've been interested in, just haven't had the time to fully investigate.

You're only option at the moment is to read each individual tag.
