### ISSUE TITLE
Handle LREAL

### ISSUE THREAD

**Issue by NothinRandom** [dmroeder/pylogix#60]
https://github.com/dmroeder/pylogix/blob/0f0299fd0f5a52bd6db71892701fe9affac8152d/pylogix/eip.py#L253

Should update to check for LREAL also because current method casts LREAL into INT:
if dataType == 202 or dataType == 203:

**Comment by dmroeder** [comment]
You are correct, I'll get that taken care of tonight.  Thanks!
