### ISSUE TITLE
Error Using Emulate ControlLogix - Exception: Forward Open Failed

### ISSUE THREAD

**Issue by rafaelmoraes33** [dmroeder/pylogix#62]
I have a problem.

I have a Studio 5000 Emulate and created a Slot with ControlLogix.

How much I try to connect is giving this error: Exception: Forward Open Failed

If I perform the Discovery function it usually appears my device and IP.

There is some specific configuration.

Attached is the image of how it is configured.

My code:

import pylogix
from pylogix import PLC
pylogixPLC = PLC()

pylogixPLC.IPAddress = "192.168.0.22"
pylogixPLC.ProcessorSlot = 2
pylogixPLC.Micro800 = False

pylogixPLC.Read('tag')

Thank you

<img width="544" alt="Screen Shot 2019-08-14 at 12 44 16 PM" src="https://user-images.githubusercontent.com/45277330/63035815-31b5a000-be92-11e9-9d19-b49dab7d8c61.png">

**Comment by dmroeder** [comment]
Emulate does not support Ethernet communication so you cannot use this library to communicate with it. You can use SoftLogix if you have it.

**Comment by rafaelmoraes33** [comment]
Many thanks for the return.

But if I use hardware from a CompactLogix would that work?

Thanks

**Comment by dmroeder** [comment]
It will work with CompactLogix over Ethernet.

**Comment by rafaelmoraes33** [comment]
It worked super well, thank you very much.

Another thing, when it is Strig type there is some way to convert as it does not come with normal characters.

Thanks

**Comment by dmroeder** [comment]
Are you reading the standard string type, or a custom length string? The standard string should be returned exactly as you see it in your program.

**Comment by dmroeder** [comment]
I have confirmed with a user that pylogix will communicate with Emulate by setting ConnectionSize to 504.

**Comment by TheFern2** [comment]
> I have confirmed with a user that pylogix will communicate with Emulate by setting ConnectionSize to 504.

I can work on adding this to the documentation sometime in the morning, do you want to perhaps do a helper param or function to active emulate mode?

**Comment by dmroeder** [comment]
I'm going to change the default fall back connection size to 504 bytes to make it compatible with emulate by default, I'll also add a not to the readme.

**Comment by TheFern2** [comment]
I'll test in the morning I got a vm with emulate I've been using for performance testing on ft linx ua. Unless you already have tested. This is huge for people that have no hardware to test until plc arrives.
