### ISSUE TITLE
GetTagList() has AttributeError: 'Response' has no attribute, 'value'

### ISSUE THREAD

**Issue by ambersnow** [dmroeder/pylogix#68]
Hi, trying to use GetTagList() via your examples in the repo but I am not having any luck getting it to work.

My code:
```python
from pylogix import PLC

with PLC() as comm:
    comm.IPAddress = '192.168.1.200'
    tags = comm.GetTagList()
    for t in tags:
	    print(t.TagName, t.DataType)
```

The trackback:
```python
Traceback (most recent call last):
  File "pylogixtest.py", line 5, in <module>
    tags = comm.GetTagList()
  File "C:\Users\Admin\Test\venv\lib\site-packages\pylogix\eip.py", line 127, in GetTagList
    updated_list = self._getUDT(tag_list.value)
AttributeError: 'Response' object has no attribute 'value'
```

Is there anything I am doing wrong or?

**Comment by Seabee1971** [comment]
I ran into a similar problem. Can you ping the 192.168.1.200?

**Comment by ambersnow** [comment]
Yep, sure can. I have 2 PLCs, one on .200 and another on .171 both giving me this same AttributeError.

**Comment by evaldes2015** [comment]
Are your PLCs in slot 0?

**Comment by ambersnow** [comment]
Yes — I even specified the `comm.ProcessorSlot = 0` but still no difference as well.

**Comment by evaldes2015** [comment]
Are the tags in the PLC configured for external access?

**Comment by ambersnow** [comment]
Yeah, they are all configured external access Read/Write. Pylogix has no problem reading/writing specific tags. Just no luck with `GetTagList()`

**Comment by evaldes2015** [comment]
Is there something weird in your tag list? Some odd character in a name perhaps? I'm guessing...

**Comment by ambersnow** [comment]
As far as I can tell, no. It’s all alphanumeric and underscores. Tags are all uppercase, if that makes a difference.

**Comment by ambersnow** [comment]
After some digging, I found what was going on. The 2nd call in `GetTagList` was looking for `tag_list.value` when the `self._getTagList` response is `tag_list.Value`. Changing line 127 from:
`updated_list = self._getUDT(tag_list.value)`
To
`updated_list = self._getUDT(tag_list.Value)`
Is what gave me a list of all the tags and tag types :)

**Comment by kodaman2** [comment]
@ambersnow  the latest version 0.4.0 has a slight change in the way the data is returned.

[23_get_all_tags example](https://github.com/dmroeder/pylogix/blob/master/pylogix/examples/23_get_all_tags.py)

Basically you have one minor error:

```
from pylogix import PLC

with PLC() as comm:
    comm.IPAddress = '192.168.1.200'
    tags = comm.GetTagList()
    for t in tags:
	    print(t.TagName, t.DataType)
```

You need to add Value in the forloop like this:

```
for t in tags.Value:
...
```

In addition to that typo as you've said there is some typos in the latest commit. Good job, submitting the PR.

**Comment by ambersnow** [comment]
No worries, this library is amazing compared to some others I've (tried to) used so anything to help contribute and make it better. :)

**Comment by kodaman2** [comment]
Awesome I've added a small comment on the PR.
