### ISSUE TITLE
The response of GetProgramTagList didn't include DataType? 

### ISSUE THREAD

**Issue by su600** [dmroeder/pylogix#75]
Hello!

When I using   
    **`tags=comm.GetProgramTagList("Program:MainProgram")`**
This function **didn't return DataType of program tags** as `tags= comm.GetTagList()`, I want get both TagName and Datatype of **program tags**, could you please check this?

Thank you

**Comment by kodaman2** [comment]
Hey su600 please ensure you have downloaded the very latest version 0.4.4 as that function had a small bug  in the previous release. 

Then try this:
```
tags = comm.GetProgramTagList("Program:MainProgram")
if tags.Value is None:
    print(tags.Status)
else:
    for t in tags.Value:
        print(t.TagName)
```

**Comment by su600** [comment]
My version is 0.4.3 now, I'll update it. 

But, anything about DataType?  Can I get DataType by GetProgramTagList?
Thanks

**Comment by kodaman2** [comment]
ok, yeah looks like a bug, even in 0.4.4, I'll try to fix it within a few days. And ensure the unittest covers both TagName and DataType.

Thanks for reporting it!

**Comment by kodaman2** [comment]
Please download repo from this commit, and let me know if it worked. Once I get the confirmation I can merge to master.

https://github.com/kodaman2/pylogix/tree/program-list-patch-02

**Comment by kodaman2** [comment]
This issue is fixed, but I'll leave issue open until confirmation.

**Comment by su600** [comment]
Yeah, It works well. 
(Something wrong I can't upload a screenshot）

`Program:MainProgram.l BOOL`
`>>> pylogix.__version__`
`'0.4.5'`

Thank you，this  issue is fixed.

**Comment by kodaman2** [comment]
Awesome, you're welcome!
