### ISSUE TITLE
SLC-5 Support

### ISSUE THREAD

**Issue by DCogent** [dmroeder/pylogix#85]
Do you have any way to connect to a SLC plc? I have tried but no luck. The exact one is a 1747-L552

**Comment by evaldes2015** [comment]
I believe the SLC speaks PCCC, not EIP.

**Comment by dmroeder** [comment]
@evaldes2015 is correct, there is no way to read/write SLC or PLC5.

**Comment by evaldes2015** [comment]
@DCogent There are libraries for talking to SLC. If you like I could point you in the right direction.
