### ISSUE TITLE
reading multidimensional array

### ISSUE THREAD

**Issue by gnail13** [dmroeder/pylogix#91]
Hi all,

I have a project that I need to retrive a two-dimensional array size of [1000][7].  How can I read it?  Thanks in advance.

Lan

**Comment by dmroeder** [comment]
You use the same syntax as in RSLogix/Logix Designer:

MyTag[0,0]

**Comment by gnail13** [comment]
Can I use indirect addressing like MyTag[i,j] to access the array other than tag.Read(MyTag[0,0], 100)?

**Comment by gnail13** [comment]
In other words can I traves the array with for loop?  So I can read the data on first dimension MyTag[i,0].

**Comment by dmroeder** [comment]
You could do something like:

```
for i in range(10):
    tag_name = 'MyTag[{},0]'.format(i)
    ret = comm.Read(tag, 100)
```

Is that what you were thinking?

**Comment by gnail13** [comment]
I am not sure that's the result I wants but I would try it.  Thank you.

**Comment by dmroeder** [comment]
First iteration would get you 100 values starting at Mytag[0,0] (MyTag[0,0-99])
Next iteration would get you 100 values starting at Mytag[1,0] (MyTag[1,0-99])
and so on

**Comment by gnail13** [comment]
Thank you dmroeder.  That's what I need.

**Comment by AlePanto** [comment]
I am having similar issues:

Need to read the entire TD_Array DINT[10,7] 

'''What is wrong with the code?'''

from pylogix import PLC

with PLC() as comm:
    comm.IPAddress = '192.168.1.15'
    ret = comm.Read('TD_Array[10,7]' )             #what do I nee to specify?
    print(ret.Value)

'''Thank you for the help'''

**Comment by dmroeder** [comment]
Install the latest version (0.8.8).  I broke something with multi dimension arrays.

**Comment by AlePanto** [comment]
I upgraded before asking on the forum! 
Well... I hope you and community can solve it. Thank you!!!

**Comment by AlePanto** [comment]
Nevermind!!!!
Iit works, Thank YOU!!!!!!!
