### ISSUE TITLE
Getting Controller logging

### ISSUE THREAD

**Issue by Quanho90** [dmroeder/pylogix#95]
I try to get controller logging which show online editing, program changes, I/O force history,etc from Controllogix and Compactlogix.
After research, I found that Allen Bradley Studio 5000 have capability to log these attributes to SD card.
Can you help me to get these information from PLC with python script?

Here is reference link:
https://literature.rockwellautomation.com/idc/groups/literature/documents/pm/1756-pm015_-en-p.pdf

**Comment by dmroeder** [comment]
This is not going to be possible to do.  While the sending the request is not that difficult to do, the controller will reject it.  The command can only come from the controller itself, it cannot come from an external source, the PLC will respond with "Privilege Violation".
